fos_elastica:
    clients:
        default: { host: "%elastic_host%", port: "%elastic_port%" }
    serializer:
        callback_class: FOS\ElasticaBundle\Serializer\Callback
        serializer: serializer
    indexes:
        app:
            client: default
            types:
                Episode:
                    mappings: ~
                    persistence:
                        driver: orm # orm, mongodb, propel are available
                        model:  AppBundle\Entity\Episode
                        provider: ~
                        finder: ~